import { LegalPageLayout } from '@/components/layout/LegalPageLayout';

export const metadata = {
  title: 'Terms of Service — Rough Idea Travel',
};

export default function TermsPage() {
  return (
    <LegalPageLayout
      title="Terms of Service"
      intro="By using Rough Idea Travel, you agree to these terms. Please read them carefully — they're written to be straightforward, not impenetrable."
      crosslinks={[
        { label: 'Privacy Policy', href: '/privacy' },
        { label: 'Cookie Policy', href: '/cookies' },
      ]}
    >
      <div className="legal-section">
        <h2>Who We Are</h2>
        <p>Rough Idea Travel is operated by Rough Idea Travel LLC. We provide an AI-powered travel planning tool that helps people discover destinations and plan trips. We are not a travel agency, airline, hotel, or booking service.</p>
      </div>

      <div className="legal-section">
        <h2>Using the Service</h2>
        <p>Rough Idea Travel is free to explore without an account. Some features — including saving wishlists and generating full itineraries — require you to create an account.</p>
        <p>You agree to:</p>
        <ul>
          <li>Provide accurate information when using the search form</li>
          <li>Use the service for personal, non-commercial trip planning</li>
          <li>Not attempt to reverse-engineer, scrape, or abuse our AI systems</li>
          <li>Not use the service in any way that violates applicable laws</li>
        </ul>
        <p>You must be at least 18 years old to create an account.</p>
      </div>

      <div className="legal-section">
        <h2>Our Content and AI Recommendations</h2>
        <p>The destination recommendations, itineraries, weather information, and cost estimates generated by Rough Idea Travel are produced by an AI system and are provided for informational purposes only.</p>
        <p>We make reasonable efforts to ensure accuracy, but we cannot guarantee that:</p>
        <ul>
          <li>Recommendations are a perfect fit for your specific needs</li>
          <li>Cost estimates reflect actual prices at time of travel</li>
          <li>Weather data is accurate for your exact travel dates</li>
          <li>Local conditions, hours, or availability are current</li>
        </ul>
        <p>Always verify important details independently before booking. We are not responsible for any decisions made based on our recommendations.</p>
      </div>

      <div className="legal-section">
        <h2>Third-Party Booking Links</h2>
        <p>Rough Idea Travel may display links to third-party booking platforms including Booking.com, Airbnb, and Google. These links may include affiliate tracking, which means we may receive a commission if you make a booking through them — at no additional cost to you. We are not responsible for the content, pricing, availability, or practices of these third-party services.</p>
      </div>

      <div className="legal-section">
        <h2>Accounts</h2>
        <p>If you create an account, you are responsible for maintaining the security of your login credentials and for all activity that occurs under your account. We reserve the right to suspend or terminate accounts that violate these terms.</p>
      </div>

      <div className="legal-section">
        <h2>Intellectual Property</h2>
        <p>The Rough Idea Travel name, logo, and product are owned by Rough Idea Travel LLC. You may not use our branding without prior written permission. Content you submit (such as wishlist names) remains yours. By submitting it, you grant us a limited licence to store and display it as part of the service.</p>
      </div>

      <div className="legal-section">
        <h2>Limitation of Liability</h2>
        <p>To the maximum extent permitted by law, Rough Idea Travel LLC shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service, including but not limited to travel disruptions, booking errors, or reliance on AI-generated recommendations. Our total liability to you for any claim shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
      </div>

      <div className="legal-section">
        <h2>Changes to These Terms</h2>
        <p>We may update these Terms of Service at any time. We will notify registered users of material changes. Continued use of the service constitutes acceptance of the updated terms.</p>
      </div>

      <div className="legal-section">
        <h2>Governing Law</h2>
        <p>These terms are governed by the laws of the State of New York, United States, without regard to conflict of law principles.</p>
      </div>

      <div className="legal-contact-box">
        <p><strong>Rough Idea Travel LLC</strong><br />hello@roughidea.co</p>
      </div>
    </LegalPageLayout>
  );
}
